In [1]:
#Array Ayırma

In [7]:
import numpy as np

In [17]:
x = np.array([1,2,3,99,99,3,2,1])

In [27]:
#başlangıçtan 3 e kadar alır geri kalanı bir dizi yapar.
# 3, 5 => 3 e kadar al dizi yap  3 den sonra 5'e kadar al dizi yap ve geri kalanlarıda ayrı bir dizi yap
np.split(x,[3,5,2])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1]), array([], dtype=int64)]

In [31]:
a,b,c = np.split(x,[3,5])

In [33]:
a

array([1, 2, 3])

In [35]:
b

array([99, 99])

In [39]:
c

array([3, 2, 1])

In [41]:
#İki boyutlu Ayırma

In [45]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#Matris'i 2. satırdan itibaren böler ve  ayrı bir matris yapar.
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [49]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]