# ARRAY SIRALAMA(SORTING)

In [8]:
import numpy as np

In [14]:
v = np.array([2,1,4,3,5])

In [18]:
v 

array([2, 1, 4, 3, 5])

In [22]:
np.sort(v) #küçükten büyüğe

array([1, 2, 3, 4, 5])

In [26]:
#İKİ BOYUTLU ARRAY SIRALAMA

In [37]:
m = np.random.normal(20,5,(3,3))

m

In [40]:
#X eksenindekileri küçükten büyüğe sıralar
np.sort(m,axis = 1 )

array([[11.56078958, 21.2671496 , 27.50253228],
       [16.28293476, 17.32601783, 21.93271775],
       [15.88104731, 20.90160146, 21.10744273]])

In [44]:
#Y eksenindekileri küçükten büyüğe sıralar
np.sort(m,axis = 0 )

array([[15.88104731, 11.56078958, 21.10744273],
       [17.32601783, 16.28293476, 21.93271775],
       [21.2671496 , 20.90160146, 27.50253228]])