# Matematiksel İşlemler


In [11]:
import numpy as np

In [13]:
v = np.array([1,23,45,12,23,12])

In [15]:
#ufunc

In [19]:
np.subtract(v,1)

array([ 0, 22, 44, 11, 22, 11])

In [21]:
np.multiply(v,2)

array([ 2, 46, 90, 24, 46, 24])

In [23]:
np.divide(v,3)

array([ 0.33333333,  7.66666667, 15.        ,  4.        ,  7.66666667,
        4.        ])

In [27]:
np.power(v,3)

array([    1, 12167, 91125,  1728, 12167,  1728])

In [30]:
v % 2 

array([1, 1, 1, 0, 1, 0])