In [3]:
import numpy as np 

In [5]:
np.array([1,23,4,5,6])

array([ 1, 23,  4,  5,  6])

In [7]:
a = np.array([1,23,4,5,6])
type(a)

numpy.ndarray

In [17]:
#Sıfırlardan oluşan bir array

np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#Satır x Sütun 
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [23]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [25]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
#Ortalam,Standart sapma
np.random.normal(10,4,(3,4))

array([[15.69895102, 11.5247387 ,  5.78039474,  8.87657619],
       [ 5.33019196, 10.37917276, 16.06507797, 16.64879855],
       [ 9.05113566,  7.48063939,  8.13687724,  7.50344064]])

In [29]:
np.random.randint(0,10,(3,3))

array([[5, 8, 8],
       [3, 4, 5],
       [3, 0, 6]])