# ARRAY ALT KÜMELERE ERİŞMEK

In [5]:
import numpy as np

In [9]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
#0 dan başla 3 eleman al ilk eleman dahil.
a[0:3]

array([20, 21, 22])

In [ ]:
#3. indeksten başla dizinin geri kalan elemanlarını al
a[3:]

In [13]:
#Birinci indeksten başka ikişer ikişer atlayarak git
a[1::2]

array([21, 23, 25, 27, 29])

In [17]:
#İKİ BOYUTLU SLİCE İŞLEMLERİ

In [23]:
m = np.random.randint(10,size = (5,5))

In [25]:
m

array([[9, 6, 4, 8, 4],
       [3, 3, 0, 6, 4],
       [9, 4, 1, 8, 7],
       [2, 3, 7, 0, 6],
       [4, 2, 1, 2, 7]])

In [35]:
#0.sütunda bütün elemanlara eriş.
m[:,0]

array([9, 3, 9, 2, 4])

In [37]:
#0.satırda bütün elemanları erişti
m[0,:]

array([9, 6, 4, 8, 4])

In [39]:
#0. satırda bütün elemanlara eriş
m[0] 

array([9, 6, 4, 8, 4])

In [41]:
#0 dan 2 ye satırları aldı 0 dan 3 kadar sütunları aldı.
m[0:2,0:3]

array([[9, 6, 4],
       [3, 3, 0]])

In [49]:
#
m[:,:2]

array([[9, 6],
       [3, 3],
       [9, 4],
       [2, 3],
       [4, 2]])